### ISSUE TITLE
Demuxer issue with udp stream

### ISSUE THREAD

**Issue by admarrs** [kim-company/membrane_mpeg_ts_plugin#4]
I don’t know if this is my setup or an issue with the plugin. I’m hitting an issue trying to get the demuxer working with a udp mpegts stream source. It plays ok with ffplay.

Connecting a pipeline with a udp source feeding a demuxer instance, it all works as far as pmt receipt but the call to Process.send_after() doesn’t result in the associated:stream_start_received handle_info being called.

Wondering if anyone has seen a similar issue?

**Comment by dmorn** [comment]
Hey there! Just to ensure your setting it up correctly: after the demuxer reads the PMT table, it sends a **notification to the parent**, usually the pipeline. That's https://github.com/kim-company/membrane_mpeg_ts_plugin/blob/d33bc1113a6eb4cc8c6f9c8c9d2343957c82e874/lib/membrane/mpeg/ts/demuxer.ex#L102

Afterwards you have to choose with your own logic which streams you want to connect to and attach the rest of you pipeline to that dynamic pad, specifying the stream id. Are we on the same page?

**Comment by dmorn** [comment]
Sorry for the non existent documentation 😅

**Comment by dmorn** [comment]
@admarrs you can use https://github.com/kim-company/membrane_mpeg_ts_plugin/blob/d33bc1113a6eb4cc8c6f9c8c9d2343957c82e874/test/membrane/mpeg/ts/demuxer_test.exs for a reference implementation!

**Comment by admarrs** [comment]
Thanks
